### PR TITLE
[GH-672] Refactor all zero to wfl.

### PR DESCRIPTION
**Pull request by rexwangcc**
### Purpose

- https://broadinstitute.atlassian.net/browse/GH-672

### Changes

- Refactor all zero to wfl (except the `zero`s in Vault paths and the cloud bucket names)
- **Note:** all occurrences of `"zero-postgresql"` are left as they are since there's no smooth way to rename an existing Cloud SQL DB instance via Google Cloud.
- Fixes https://broadinstitute.atlassian.net/browse/GH-944

### Review Instructions

- Sibling PRs: 
    - https://github.com/broadinstitute/pipeline-config/pull/54
    - https://github.com/broadinstitute/gotc-deploy/pull/144

### CODE REVIEW

**Review by samanehsan — APPROVED** [review]

**Review by jack-r-warren — CHANGES_REQUESTED** [review]
In `docs/md/dev-process.md`:168 there's a reference to `postgres/zero-db-url`.

In `helm/wfl/values.yaml`:26-27 there's references to `ZERO_POSTGRES_PASSWORD`/`ZERO_POSTGRES_PASSWORD`. The deployment script is the only consumer, I believe, and it [will already prioritize use of `WFL_POSTGRES_PASSWORD`/`WFL_POSTGRES_PASSWORD`](https://github.com/broadinstitute/wfl/blob/master/ops/cli.py#L186) if it finds them. We could change the values file here and also the two values files in `gotc-deploy` and that would be a little bit more of zero gone, I don't know if that's worth it.

**Comment by jack-r-warren** [comment]
Also @rexwangcc I'm more than happy to help out on making those changes I mentioned above, just didn't want to commit to your branch without saying something. I wish it was possible to suggest edits to files not in the PR.

**Comment by rexwangcc** [comment]
> In `docs/md/dev-process.md`:168 there's a reference to `postgres/zero-db-url`.
> 
> In `helm/wfl/values.yaml`:26-27 there's references to `ZERO_POSTGRES_PASSWORD`/`ZERO_POSTGRES_PASSWORD`. The deployment script is the only consumer, I believe, and it [will already prioritize use of `WFL_POSTGRES_PASSWORD`/`WFL_POSTGRES_PASSWORD`](https://github.com/broadinstitute/wfl/blob/master/ops/cli.py#L186) if it finds them. We could change the values file here and also the two values files in `gotc-deploy` and that would be a little bit more of zero gone, I don't know if that's worth it.

Thanks!

I think the reference to `postgres/zero-db-url` is outdated and shall be removed, I will try to clean up the docs shortly.

> Also @rexwangcc I'm more than happy to help out on making those changes I mentioned above, just didn't want to commit to your branch without saying something. I wish it was possible to suggest edits to files not in the PR.

No worries and thanks, I can make those changes in Vault!

**Comment by jack-r-warren** [comment]
> No worries and thanks, I can make those changes in Vault!

Just a heads up that the values files in gotc-deploy will have to change too

**Review by jack-r-warren — APPROVED** [review]
LGTM--reviewed in tandem with https://github.com/broadinstitute/gotc-deploy/pull/144 and it matches up to my eye

**Pull request merged**
