### PR TITLE
Release 0.18.1 to pick up ExternalWholeGenomeReprocessing_v2.0.5.

### PR DESCRIPTION
**Pull request by tbl3rd**
### Purpose

- https://broadinstitute.atlassian.net/browse/GH-1646

### Changes

- [GH-1644](https://broadinstitute.atlassian.net/browse/GH-1644) Drop delete-directory and copy-directory from wfl.util.
- [GH-1645](https://broadinstitute.atlassian.net/browse/GH-1645) Update wfl.module.wgs/workflow-wdl to run a new WDL that allows overriding read_length in Collect*Metrics.
- [GH-1646](https://broadinstitute.atlassian.net/browse/GH-1646) Deploy 0.18.1 to pick up ExternalWholeGenomeReprocessing_v2.0.5.
- Remove some unused bindings and code.

### Review Instructions

```
tbl@wmf05-d86 ~/Broad/wfl # time make api TARGET=system
export CPCACHE=/Users/tbl/Broad/wfl/api/.cpcache;            \
    export WFL_WFL_URL=http://localhost:3000; \
    clojure  -M:parallel-test wfl.system.v1-endpoint-test | \
    tee /Users/tbl/Broad/wfl/derived/api/system.log
WARNING: Use of :paths external to the project has been deprecated, please remove: ../derived/api/src
WARNING: Use of :paths external to the project has been deprecated, please remove: ../derived/api/resources

### CODE REVIEW

**Review by okotsopoulos — CHANGES_REQUESTED** [review]
Do you remember how you created this release branch? I am concerned about the “files changed” which look like changes dating back from several releases, rather than the changes for this specific release. May also be causing the merge conflicts. Happy to chat more tomorrow.

**Comment by tbl3rd** [comment]
I branched from develop, updated the CHANGELOG and version, and changed the base to main.

**Comment by sjacobs146** [comment]
We actually create the release branch from main and merge changes from develop branch into the release branch

**Comment by tbl3rd** [comment]
Working on tbl/release/0.18.1-rc now, but the a TDR request throws from the system test.

**Pull request closed without merging**
