### PR TITLE
[GH-1654] Admit memory retry multiplier.

### PR DESCRIPTION
**Pull request by tbl3rd**
### Purpose

- https://broadinstitute.atlassian.net/browse/GH-1654

### Changes

- Add a `memory_retry_multiplier` column to the `TerraExecutor` table.
- Map `:memoryRetryMultiplier` workload `executor` attribute to the new column.
- Test that the new attribute round-trips through the database.

### Review Instructions

- No instructions.

### CODE REVIEW

**Review by aednichols — APPROVED** [review]

**Review by okotsopoulos — CHANGES_REQUESTED** [review]
What is this ticket trying to accomplish?  Is it meant to allow a caller to set a memory retry multiplier for Terra submissions?

Presently while this multiplier is saved in the DB, WFL doesn't do anything with it.  The executor will also need to be altered to pass this multiplier to Rawls / Firecloud when initiating a submission.

**Comment by tbl3rd** [comment]
Thanks. Wanna give this another look, @okotsopoulos ?

**Review by okotsopoulos — APPROVED** [review]
That looks like it should do it, thanks.

It would be nice to include this new supported executor field in the public-facing docs, I know Morgan and Sushma reference them: https://broadinstitute.github.io/wfl/staged-executor/#terra-executor

**Comment by tbl3rd** [comment]
Good idea. Will do.

**Pull request merged**
