### PR TITLE
[GH-1586] Release 0.12.1 to AoU prod to pick up the version Arrays_v2.6.3 WDL.

### PR DESCRIPTION
**Pull request by tbl3rd**
### Purpose

- https://broadinstitute.atlassian.net/browse/GH-1586

### Changes

- [GH-1586] Run AoU pipeline with the Arrays_v2.6.3 WDL. ([#557](https://github.com/broadinstitute/wfl/pull/557))
- [GH-1527] Remove Firecloud calls when fetching TerraExecutor workflows ([#543](https://github.com/broadinstitute/wfl/pull/543))

### Review Instructions

- The commit list is rubbish, as usual.

[GH-1586]: https://broadinstitute.atlassian.net/browse/GH-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GH-1527]: https://broadinstitute.atlassian.net/browse/GH-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gbggrant — APPROVED** [review]
Sure, I guess?

**Comment by tbl3rd** [comment]
> Sure, I guess?

Works for me.

**Review by okotsopoulos — APPROVED** [review]
The contents look good.  I would vote for 0.13.0 as the release version though, since my "remove Firecloud calls…" PR is on the larger side.

Thanks!

**Comment by tbl3rd** [comment]
> The contents look good. I would vote for 0.13.0 as the release version though, since my "remove Firecloud calls…" PR is on the larger side.
> 
> Thanks!

You're probably right, but too late.

**Pull request merged**
